### ISSUE TITLE
在博客已经部署好的基础上，如何部署cv呢？

### ISSUE THREAD

**Issue by nick-zhy** [JoeyBling/cv#1]
我已经部署好了博客，想通过博客的简历按钮进入简历页面，而这个简历页面不是一个简单的博客的文章。就像您回复的，需要用模板再部署一次。在username.github.io已经部署好了，怎么部署cv的页面呢？
小白一枚，主要就想打造一个中英文cv方便以后申请phd用。
希望您不吝赐教。

**Comment by JoeyBling** [comment]
你把简历项目部署好后，开启pages服务，和之前博客的操作一样，然后通过 `username.github.io/简历仓库名`  访问即可
比如我博客放在：https://github.com/JoeyBling/JoeyBling.github.io 访问地址：https://joeybling.github.io/
简历放在：https://github.com/JoeyBling/cv 访问地址：https://joeybling.github.io/cv

**Comment by JoeyBling** [comment]
理论上就是博客域名下的子目录映射了，同理可以有多个仓库开启pages服务

**Comment by nick-zhy** [comment]
我还有两个问题
1. 简历的仓库地址应该怎么设置？username.github.io/resume么？
2. 本地的简历模板应该放在哪里呢，需要放在blog文件夹内吗？
3. 简历和博客其实相当于是分别部署，分开编译的是吧？只是博客中有导向简历的一个链接？

**Comment by JoeyBling** [comment]
1. 仓库地址随你自己喜欢命名即可，仓库名就是访问的网址后缀
2. 放根目录就行
3. 是的，不同仓库就是不同项目，在博客写了个链接过去而已，理论上就是2套系统，你想在一套系统有个链接体现另外一个系统都是随你自己的
