### ISSUE TITLE
博客

### ISSUE THREAD

**Issue by AnthonyZero** [JoeyBling/cv#2]
我现在有hexo 的博客。
请问怎么把这块内容  添加到我博客的一个新分类上面。

**Comment by JoeyBling** [comment]
添加一个博客项目仓库（命名自己定义），然后开启gh-pages服务即可。再到Hexo博客里添加一个菜单链接到博客的主页即可

**Comment by JoeyBling** [comment]
可以参考之前提出的
> https://github.com/JoeyBling/cv/issues/1
